import { CheckCircle2 } from "lucide-react";
import { formatHeightDual, formatWeightDual } from "@/lib/catalog/productSpecs";
import type { Product } from "@/types/product";

export function DollDetailsCard({ product }: { product: Product }) {
  const details = [
    ["Brand", product.extended.brand ?? product.vendor],
    ["Material", product.extended.material ?? "Ask us"],
    ["Height", formatHeightDual(product.extended.heightCm) || "Ask us"],
    ["Weight", formatWeightDual(product.extended.weightLb) || "Ask us"],
    ["Cup size", product.extended.cupSize || "Ask us"],
    ["Delivery", product.extended.deliveryEstimate ?? "Typical timing depends on the build"],
    ["Warehouse", product.extended.warehouseRegions?.join(", ") || product.extended.warehouseCountry || "Ask us"]
  ];

  return (
    <section className="rounded-[20px] border border-gold-500/16 bg-ink-800/72 p-6">
      <div className="mb-5 flex items-center gap-3">
        <CheckCircle2 className="h-5 w-5 text-gold-400" />
        <div>
          <h2 className="text-xl font-semibold text-ivory-50">Product details</h2>
          <p className="text-sm text-ivory-400">Key specifications and delivery details.</p>
        </div>
      </div>
      <dl className="grid gap-3 sm:grid-cols-2">
        {details.map(([label, value]) => (
          <div key={label} className="rounded-[14px] bg-ink-950/45 p-4">
            <dt className="text-sm  text-ivory-600">{label}</dt>
            <dd className="mt-1 text-sm font-semibold text-ivory-100">{value}</dd>
          </div>
        ))}
      </dl>
      <p className="mt-4 text-sm leading-6 text-ivory-400">{cleanNote(product.extended.qcNote)}</p>
    </section>
  );
}

export function cleanNote(note?: string) {
  if (!note) return "Need help with a detail? Our team is here to help.";
  if (/\b(?:rosemary(?:doll)?|joy\s*love|joylovedolls?)\b|\b(?:catalog logic|source of truth|reviewed pricing|internal review)\b/i.test(note)) {
    return "Questions about this configuration? Our team can confirm the details before you order.";
  }
  return note
    .replace(/^Prepared from .*?\. Review supplier authorization, pricing, images, and option mapping before publish\.$/i, "Need help with a detail? Our team is here to help.")
    .replace(/Draft import generated by DollWow\.[^.]*\./gi, "Need help with a detail? Our team is here to help.");
}
